name: Deploy to preview
on:
  push:
    branches:
    - preview
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout github
      uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.62.1'
        extended: true

    - run: hugo --minify

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        repository-name: catskillpreservation/preview
        branch: main
        folder: public
        token: ${{ secrets.DEPLOY_TOKEN }}
        clean-exclude: |
          CNAME
