name: Deploy to Main and Preview

on:
  push:
    branches:
    - main
    - preview
  workflow_dispatch:
  repository_dispatch:

jobs:
  build-main:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout github
      uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.DEPLOY_TOKEN }}
        ref: 'main'

    - name: Add comment submodule
      uses: actions/checkout@v2
      with:
        repository: catskillpreservation/P-15056-000-comments
        path: content/comments/P-15056-000
        token: ${{ secrets.DEPLOY_TOKEN }}
        ref: 'main'


    
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.62.1'
        extended: true

    - run: hugo --minify

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        repository-name: catskillpreservation/catskillpreservation.github.io
        branch: main
        folder: public
        token: ${{ secrets.DEPLOY_TOKEN }}
        clean-exclude: |
          CNAME
          404.md

  build-preview:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout github
      uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.DEPLOY_TOKEN }}
        ref: 'preview'
        
    - name: Add comment submodule
      uses: actions/checkout@v2
      with:
        repository: catskillpreservation/P-15056-000-comments
        path: content/comments/P-15056-000
        token: ${{ secrets.DEPLOY_TOKEN }}
        ref: 'main'

    
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.62.1'
        extended: true

    - run: hugo --minify

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        repository-name: catskillpreservation/preview
        branch: main
        folder: public
        token: ${{ secrets.DEPLOY_TOKEN }}
        clean-exclude: |
          CNAME
