name: Deploy to catstillpreservation.github.io

on:
  push:
    branches:
    - main

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout github
      uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.62.1'
        extended: true

    - run: hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        external_repository: catstillpreservation/catstillpreservation.github.io
        PUBLISH_BRANCH: main
        PUBLISH_DIR: ./public
        CNAME: catstillpreservation.com
        allow_empty_commit: true
