
name: Update Submodules

on:
    workflow_dispatch:


jobs:
  update:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout github
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.DEPLOY_TOKEN }}
      - name: Update submodules
        run: |
          cd ./content/comments/P-15056-000
          git pull
      - name: Commit submodules
        run: |
          git config user.name sommea
          git config user.email asommer999@gmail.com
          git commit -m "Added license headers" || echo "No changes to commit"
          git push

          
