
name: Update Submodules

on:
    workflow_dispatch:


jobs:
  update:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout github
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Update submodules
        run: |
          git submodule foreach git pull origin master
      - name: Commit submodules
        run: |
          git config user.name sommea
          git config user.email asommer999@gmail.com
          git commit -m "Updated submodules"
          git push

          
