
name: update comment submodule

on:
    workflow_dispatch:
    repository_dispatch:


jobs:
  update:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout github
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.DEPLOY_TOKEN }}
      - name: update submodules
        run: |
            cd ./content/comments/P-15056-000
            git config user.name sommea
            git config user.email asommer999@gmail.com
            git pull origin main --allow-unrelated-histories
      - name: commit submodules
        run: |
            git config user.name sommea
            git config user.email asommer999@gmail.com
            git add .
            git commit -m "Updated submodules" || echo "No changes to commit"
            git push
            git submodules update --init --recursive


          
